#!/bin/sh

which doas 1> /dev/null 2> /dev/null 3> /dev/null && asRoot=doas
which sudo 1> /dev/null 2> /dev/null 3> /dev/null && asRoot=sudo

buildRelease(){
  $asRoot docker build -t mvc .
}
release(){
  $asRoot docker run -p 443:443 -itd mvc
}
buildDev(){
  $asRoot docker build -t mvc:dev -f DockerfileDev .
}
devServer(){
  $asRoot docker run --rm -it --volume $PWD/src/:/var/www/html/ mvc
}

case $1 in
  "build-release")
    buildRelease ;;
  "release")
    release ;;
  "build-dev")
    buildDev ;;
  "dev-server")
    devServer ;;
  *)
    printf "Usage:\n\nbuild-release      build a release image\nbuild-dev          build a dev image\ndev-server         launch a local dev server\n";;
esac
